FROM node:22-alpine

WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install --production

# Copia o restante do código
COPY . .

# Expõe a porta que o servidor Node utiliza
EXPOSE 3000

# Comando para iniciar o backend
CMD ["node", "server.js"]
