FROM node:22-bookworm-slim

WORKDIR /app

ENV NODE_ENV=production

# Dependências Oracle Instant Client
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        unzip \
        libaio1 \
        libnsl2 && \
    rm -rf /var/lib/apt/lists/*


# Oracle Instant Client 19c
RUN mkdir -p /opt/oracle && \
    curl -fsSL \
    https://download.oracle.com/otn_software/linux/instantclient/1932000/instantclient-basic-linux.x64-19.32.0.0.0dbru.zip \
    -o /tmp/instantclient.zip && \
    unzip -q /tmp/instantclient.zip -d /opt/oracle && \
    rm /tmp/instantclient.zip && \
    echo "/opt/oracle/instantclient_19_32" \
        > /etc/ld.so.conf.d/oracle-instantclient.conf && \
    ldconfig

ENV LD_LIBRARY_PATH=/opt/oracle/instantclient_19_32


# Dependências Node
COPY package.json package-lock.json ./

RUN npm ci --omit=dev

COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
